// When the client calls the method, it will execute the stub method 
// on the client-side, which can quickly return a (predicted) response. 
// When the server comes back with the ‘actual’ response, it will replace 
// the response generated by the stub and update other elements according.

Meteor.methods({
  newMessage: function (message) {
    message.timestamp = Date.now();
    message.user = Meteor.userId();
    Messages.insert(message);
  }
});