// When the client calls the method, it will execute the stub method 
// on the client-side, which can quickly return a (predicted) response. 
// When the server comes back with the ‘actual’ response, it will replace 
// the response generated by the stub and update other elements according.

Meteor.methods({
  newMessage: function (message) {
    message.timestamp = Date.now();
    message.user = Meteor.userId();
    Messages.insert(message);
  },

  newShow: function (show) {
  	var num = Math.random(); // this will get a number between 0 and 1.
	  num *= Math.floor(Math.random()*2) == 1 ? 1 : -1; // this will add minus sign in 50% of cases
    show.nameShow = show.name
    show.user = Meteor.userId();
    show.counter = 0;
    show.latitude = 43.4667 + num;
    show.longitude = -80.5167 + num;
    Shows.insert(show);
  }
});