// When the client calls the method, it will execute the stub method 
// on the client-side, which can quickly return a (predicted) response. 
// When the server comes back with the ‘actual’ response, it will replace 
// the response generated by the stub and update other elements according.

Meteor.methods({
  newMessage: function (message) {
    message.timestamp = Date.now();
    message.user = Meteor.userId();
    Messages.insert(message);
  },

  newEvent: function (occurence) {
  	var num = Math.random(); // this will get a number between 0 and 1.
	num *= Math.floor(Math.random()*2) == 1 ? 1 : -1; // this will add minus sign in 50% of cases

    occurence.timestamp = Date.now();
    occurence.user = Meteor.userId();
    occurence.name = "Dr. Who";
    occurence.counter = 0;
    occurence.latitude = 43.4667 + num;
    occurence.longitude = -80.5167 + num;
    Events.insert(occurence);
  }
});